repos:
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args:
            - --line-length=120

-   repo: https://github.com/timothycrosley/isort
    rev: 5.11.5
    hooks:
    -   id: isort
        additional_dependencies: [ toml ]
        args:
            - --profile=black
            - --line-length=120

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
        files: ^(?!.*\.cfn\.yaml$).*\.yaml$     # Check all yaml files except the AWS Cloud Formation scripts .cfn.yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]
        args: ['--ignore=E203, E501, W503']

-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
    -   id: pydocstyle
        args:
        - --convention=google

-   repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v1.29.1  # Use the latest version
    hooks:
    -   id: cfn-lint
        files: \.cfn\.yaml$  # The Cloud Formation scripts should be suffixed with .cfn.yaml to be tested

-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks